#requires -Version 5.1

<#
.SYNOPSIS
Registers the Copilot usage pipeline as a daily Windows Scheduled Task.

.DESCRIPTION
Creates or replaces a Windows Scheduled Task that runs
Invoke-CopilotUsagePipeline.ps1 once per day. Before registration, the script
checks that the configured certificate exists in Cert:\CurrentUser\My and has
an accessible private key.

The task uses the current Windows user's interactive token and limited
privileges. It can run while that user's session is locked, but the user must
remain signed in. StartWhenAvailable allows a missed trigger to run after the
machine becomes available.

.PARAMETER ConfigPath
Path to the pipeline JSON configuration generated by
New-CopilotUsageApp.ps1.

.PARAMETER TaskName
Name shown in Windows Task Scheduler. An existing task with this name is
replaced.

.PARAMETER DailyAt
Local daily start time in 24-hour HH:mm format.

.OUTPUTS
None.

.EXAMPLE
.\Register-CopilotUsageScheduledTask.ps1 `
    -ConfigPath '.\automation.config.json' `
    -TaskName 'M365 Copilot Usage Export' `
    -DailyAt '06:00'

Registers the pipeline to run every day at 06:00 local time.

.NOTES
This registration mode is suitable for a workstation or demo environment. For
a production service that must run with no interactive Windows session,
consider Azure Automation, an Azure Function, or a dedicated service identity
with an appropriately protected certificate.
#>

[CmdletBinding()]
param(
    [string]$ConfigPath = (Join-Path $PSScriptRoot 'automation.config.json'),

    [string]$TaskName = 'M365 Copilot Usage Export',

    [ValidatePattern('^\d{2}:\d{2}$')]
    [string]$DailyAt = '06:00'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$resolvedConfigPath = (Resolve-Path -LiteralPath $ConfigPath).Path
$config = Get-Content -LiteralPath $resolvedConfigPath -Raw | ConvertFrom-Json
$certificate = Get-Item -LiteralPath "Cert:\CurrentUser\My\$($config.CertificateThumbprint)" -ErrorAction Stop
if (-not $certificate.HasPrivateKey) {
    throw 'The configured certificate does not have an accessible private key for the current Windows user.'
}

$pipelinePath = Join-Path $PSScriptRoot 'Invoke-CopilotUsagePipeline.ps1'
$powerShellPath = (Get-Command powershell.exe -ErrorAction Stop).Source
$arguments = "-NoProfile -NonInteractive -ExecutionPolicy Bypass -File `"$pipelinePath`" -ConfigPath `"$resolvedConfigPath`""
$action = New-ScheduledTaskAction -Execute $powerShellPath -Argument $arguments -WorkingDirectory $PSScriptRoot
$triggerTime = [datetime]::Today.Add([timespan]::ParseExact($DailyAt, 'hh\:mm', [Globalization.CultureInfo]::InvariantCulture))
$trigger = New-ScheduledTaskTrigger -Daily -At $triggerTime
$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Hours 1)
$identity = [Security.Principal.WindowsIdentity]::GetCurrent().Name
$principal = New-ScheduledTaskPrincipal -UserId $identity -LogonType Interactive -RunLevel Limited

$task = New-ScheduledTask `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Description 'Exports Microsoft 365 Copilot usage and Entra user properties, then uploads CSV snapshots to SharePoint.'

Register-ScheduledTask -TaskName $TaskName -InputObject $task -Force | Out-Null
Write-Information "Registered scheduled task '$TaskName' for $DailyAt daily as $identity." -InformationAction Continue
Write-Warning 'The demo task runs while this Windows user is signed in, including when the session is locked.'
